# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mozzi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'FSCalendar'
      pod 'SnapKit', '~> 5.6.0'
      pod 'Alamofire'
      pod 'SwiftyJSON'
      pod 'SDWebImage'
      pod 'Gifu'
      pod 'NMapsMap'
      pod 'Kingfisher'
  # Pods for Mozzi

end
